[package]
name = "core"
version = "0.0.1"
edition = "2021"

[dependencies]
signature-validator = { path = "../signature-validator" }
extractor = { path = "../extractor" }

[features]
private_tests = []