[book]
authors = ["Vikas Rushi"]
language = "en"
multilingual = false
src = "src"
title = "ZKPDF Documentation"

[output.html]
mathjax-support = true
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/privacy-ethereum/zkpdf"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/privacy-ethereum/zkpdf/edit/main/docs/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.playground]
editable = true
copyable = true
copyable-method = "ferris"
